import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/ui/globals.css"
import React, { FunctionComponent, ReactNode } from "react"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = {
  children: ReactNode
}

const RootLayout: FunctionComponent<Props> = ({ children }) => {
  return (
    <html lang="en">
    <body className={`${inter.className} bg-clr-bg text-clr-text`}
          suppressHydrationWarning={true}>
    {children}
    </body>
    </html>
  )
}

export default RootLayout
